config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root              'static_pages#home'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'signup'  =>  'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
	  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  	<%= csrf_meta_tags %>
		<!--[if lt IE 9]>
	  		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	  		</script>
		<![endif]-->
	</head>
	<body>
	    <header>
		      <div>
		        <%= link_to "sample app", root_path, id: "logo" %>
		        <nav>
		          <ul>
		            <li><%= link_to "Home",   root_path %></li>
		            <li><%= link_to "Help",   help_path %></li>
		            <% if logged_in? %>
		            	<li><%= link_to "Profile", current_user %></li>
              			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
              			<li><%= link_to "Log out", logout_path, method: "delete" %></li>
	            	<% else %>
		            	<li><%= link_to "Log in", login_path %></li>
		            	<li><%= link_to "Sign up", signup_path %></li>
		            <% end %>
		            
		          </ul>
		        </nav>
		      </div>
	    </header>
	    <div>
	      <%= yield %>
	    </div>
	</body>
</html>